FROM amacneil/dbmate:2.6.0
# FROM ${REPOSITORY_BASE_URI}/amacneil/dbmate:2.4.0
# amacneil/dbmate:2.4.0

# Your migrations scripts are in the sql/migrations directory
COPY supabase/migrations db/migrations
